export const config = {
  APPWRITE_ID: process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID,
  APPWRITE_ENDPOINT: process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT,
  APPWRITE_DB_COLLECTION_ID: process.env.EXPO_PUBLIC_APPWRITE_DB_COLLECTION_ID,
}
